<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GujaratTalukaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('talukas')->insert([
            //Ahmedabad
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Ahmadabad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Bavla',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Daskroi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Detroj-Rampura',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Dhandhuka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Dholera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Dholka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Mandal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Sanand',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '1',
                'taluka' => 'Viramgam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Amrelli
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Amreli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Babra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Bagasara',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Dhari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Jafrabad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Khambha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Kunkavav vadia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Lathi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Lilia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Rajula',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '2',
                'taluka' => 'Savarkundla',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Anand
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Anand',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Anklav',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Borsad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Khambhat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Petlad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Sojitra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Tarapur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '3',
                'taluka' => 'Umreth',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Aravalli
            [
                'state_id' => '1',
                'city_id' => '4',
                'taluka' => 'Bayad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '4',
                'taluka' => 'Bhiloda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '4',
                'taluka' => 'Dhansura',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '4',
                'taluka' => 'Malpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '4',
                'taluka' => 'Meghraj',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '4',
                'taluka' => 'Modasa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Banaskantha
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Amirgadh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Bhabhar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Danta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Dantiwada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Deesa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Deodar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Dhanera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Kankrej',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Lakhani',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Palanpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Suigam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Tharad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Vadgam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '5',
                'taluka' => 'Vav',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Bharuch
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Bharuch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Amod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Ankleshwar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Hansot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Jambusar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Jhagadia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Netrang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Vagra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '6',
                'taluka' => 'Valia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Bhavnagar
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Bhavnagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Gariadhar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Ghogha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Jesar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Mahuva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Palitana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Sihor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Talaja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Umrala',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '7',
                'taluka' => 'Vallabhipur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Botad
            [
                'state_id' => '1',
                'city_id' => '8',
                'taluka' => 'Botad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '8',
                'taluka' => 'Barwala',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '8',
                'taluka' => 'Gadhada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '8',
                'taluka' => 'Ranpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Chhota Udaipur
            [
                'state_id' => '1',
                'city_id' => '9',
                'taluka' => 'Chhota Udaipur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '9',
                'taluka' => 'Bodeli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '9',
                'taluka' => 'Jetpur pavi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '9',
                'taluka' => 'Kavant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '9',
                'taluka' => 'Nasvadi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '9',
                'taluka' => 'Sankheda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Dahod
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Dahod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Devgadh baria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Dhanpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Fatepura',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Garbada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Limkheda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Sanjeli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Jhalod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '10',
                'taluka' => 'Singvad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Dang
            [
                'state_id' => '1',
                'city_id' => '11',
                'taluka' => 'Ahwa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '11',
                'taluka' => 'Subir',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '11',
                'taluka' => 'Waghai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Devbhoomi Dwarka
            [
                'state_id' => '1',
                'city_id' => '12',
                'taluka' => 'Bhanvad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '12',
                'taluka' => 'Kalyanpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '12',
                'taluka' => 'Khambhalia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '12',
                'taluka' => 'Okhamandal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Gandhinagar
            [
                'state_id' => '1',
                'city_id' => '13',
                'taluka' => 'Gandhinagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '13',
                'taluka' => 'Dehgam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '13',
                'taluka' => 'Kalol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '13',
                'taluka' => 'Mansa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Gir Somnath
            [
                'state_id' => '1',
                'city_id' => '14',
                'taluka' => 'Gir-Gadhada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '14',
                'taluka' => 'Kodinar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '14',
                'taluka' => 'Sutrapada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '14',
                'taluka' => 'Talala',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '14',
                'taluka' => 'Una',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '14',
                'taluka' => 'Veraval-Patan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Jamnagar
            [
                'state_id' => '1',
                'city_id' => '15',
                'taluka' => 'Jamnagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '15',
                'taluka' => 'Dhrol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '15',
                'taluka' => 'Jamjodhpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '15',
                'taluka' => 'Jodiya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '15',
                'taluka' => 'Kalavad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '15',
                'taluka' => 'Lalpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Junagadh
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Junagadh City',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Junagadh Rural',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Bhesana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Keshod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Malia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Manavadar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Mangrol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Mendarda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Vanthali',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '16',
                'taluka' => 'Visavadar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Kheda
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Kheda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Galteshwar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Kapadvanj',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Kathlal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Mahudha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Matar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Mehmedabad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Nadiad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Thasra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '17',
                'taluka' => 'Vaso',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Kutch
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Abdasa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Anjar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Bhachau',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Bhuj',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Gandhidham',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Lakhpat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Mandvi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Mundra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Nakhatrana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '18',
                'taluka' => 'Rapar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Mahisagar
            [
                'state_id' => '1',
                'city_id' => '19',
                'taluka' => 'Balasinor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '19',
                'taluka' => 'Kadana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '19',
                'taluka' => 'Khanpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '19',
                'taluka' => 'Lunawada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '19',
                'taluka' => 'Santrampur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '19',
                'taluka' => 'Virpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Mehsana
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Mehsana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Becharaji',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Jotana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Kadi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Kheralu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Satlasana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Unjha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Vadnagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Vijapur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '20',
                'taluka' => 'Visnagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Morbi
            [
                'state_id' => '1',
                'city_id' => '21',
                'taluka' => 'Halvad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '21',
                'taluka' => 'Maliya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '21',
                'taluka' => 'Morbi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '21',
                'taluka' => 'Tankara',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '21',
                'taluka' => 'Wankaner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Narmada
            [
                'state_id' => '1',
                'city_id' => '22',
                'taluka' => 'Dediapada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '22',
                'taluka' => 'Garudeshwar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '22',
                'taluka' => 'Nandod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '22',
                'taluka' => 'Sagbara',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '22',
                'taluka' => 'Tilakwada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Navsari
            [
                'state_id' => '1',
                'city_id' => '23',
                'taluka' => 'Navsari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '23',
                'taluka' => 'Vansda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '23',
                'taluka' => 'Chikhli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '23',
                'taluka' => 'Gandevi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '23',
                'taluka' => 'Jalalpore',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '23',
                'taluka' => 'Khergam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //	Panchmahal
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Ghoghamba',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Godhra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Halol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Jambughoda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Kalol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Morwa Hadaf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '24',
                'taluka' => 'Shehera',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Patan
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Patan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Chanasma',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Harij',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Radhanpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Sami',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Sankheswar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Santalpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Sarasvati',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '25',
                'taluka' => 'Sidhpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Porbandar
            [
                'state_id' => '1',
                'city_id' => '26',
                'taluka' => 'Porbandar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '26',
                'taluka' => 'Kutiyana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '26',
                'taluka' => 'Ranavav',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //	Rajkot
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Rajkot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Dhoraji',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Gondal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Jamkandorna',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Jasdan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Jetpur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Kotada Sangani',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Lodhika',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Paddhari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Upleta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '27',
                'taluka' => 'Vinchchiya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Sabarkantha
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Himatnagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Idar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Khedbrahma',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Poshina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Prantij',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Talod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Vadali',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '28',
                'taluka' => 'Vijaynagar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //	Surat
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Surat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Bardoli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Choryasi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Kamrej',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Mahuva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Mandvi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Mangrol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Olpad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Palsana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '29',
                'taluka' => 'Umarpada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Surendranagar
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Chotila',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Chuda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Dasada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Dhrangadhra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Lakhtar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Limbdi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Muli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Sayla',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Thangadh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '30',
                'taluka' => 'Wadhwan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Tapi
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Nizar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Songadh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Uchhal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Valod',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Vyara',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Kukarmunda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '31',
                'taluka' => 'Dolvan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Vadodara
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Vadodara',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Dabhoi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Desar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Karjan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Padra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Savli',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Sinor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '32',
                'taluka' => 'Waghodia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Valsad
            [
                'state_id' => '1',
                'city_id' => '33',
                'taluka' => 'Valsad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '33',
                'taluka' => 'Dharampur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '33',
                'taluka' => 'Kaprada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '33',
                'taluka' => 'Pardi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '33',
                'taluka' => 'Umbergaon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'state_id' => '1',
                'city_id' => '33',
                'taluka' => 'Vapi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
